# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GymTemplateiOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!


  pod 'NVActivityIndicatorView'
  pod 'R.swift'
  pod 'SDWebImage'
  pod 'FSCalendar'
  pod 'DropDown'
  pod 'IQKeyboardManager'
  pod 'Alamofire'
 
  # Pods for GymTemplateiOS

end
